### ISSUE TITLE
Fix/Test Responsiveness on Actual Mobile Device

### ISSUE THREAD

**Issue by JoshTheDerf** [Tribex/tribex.github.io#1]
Due to the fact I don't _own_ a small enough device to test the smallest scale of responsiveness, and some inconsistencies with the Chrome dev tools, I can't tell how well the dropdown menu actually works.

Help from someone with a phone or related would be appreciated. :3

**Comment by Nateowami** [comment]
Screenshots:

On loading:
![screenshot_2015-05-25-19-07-28](https://cloud.githubusercontent.com/assets/6140710/7796449/f3158008-0311-11e5-9e00-1ef794e8dc11.png)

Scrolling down:
![screenshot_2015-05-25-19-07-39](https://cloud.githubusercontent.com/assets/6140710/7796450/f316bc52-0311-11e5-8b70-c8fe183516f0.png)

The menu:
![screenshot_2015-05-25-19-07-48](https://cloud.githubusercontent.com/assets/6140710/7796448/f315862a-0311-11e5-87a6-e4bb95cdc1d0.png)

The only issue I found is that it's not possible to close the menu again by tapping the hamburger menu. You have to reload the page.

Edit: You should probably also change the layout of the background so more of the kittens show up and less vertical space is consumed. I love this new theme.

**Comment by JoshTheDerf** [comment]
Thanks a lot! I didn't even know you guys had a (relatively modern) smartphone. :P 

At the moment it's not possible to tap the hamburger menu. (It actually doesn't do anything, the top bar does.) I used a rather ugly set of CSS "hacks" to do it. I'll think through a more proper way to do so. 
To get rid of the menu just tap on a part of the page that's not part of the navigation.

The kittens are placeholders from http://placekitten.com/. Best site ever. How do you recommend showing more of them? (I highly agree though.)

Glad you're liking the theme! It's a bit too "modern" for my taste but that's what the rage is these days. x]

**Comment by Nateowami** [comment]
A friend gave it to our dad last year, but he didn't start using it until his previous phone started to die (it was an old Nokia).

**Comment by JoshTheDerf** [comment]
Ah, alright. Waaaait... Old Nokias don't die. They're invincible.

Also, the kitten situation should be a bit better in the latest commit. I also fixed the margin on the hamburger menu button.

**Comment by Nateowami** [comment]
Sorry, forgot to comment about background.

I really don't know, but you could try `background-size: cover;`. I have no idea if that would help. I just know it has something to do with it.

**Comment by JoshTheDerf** [comment]
@Nateowami Ah, right. That's what you meant.
Actually, I already tried that. Since the image size is 1600x600, `background-size: cover;` isn't going to have any difference unless you have a resolution greater than that. `background-size: contain;` would be a bit better, but it starts repeating on the y-axis on small screens.

**Comment by Nateowami** [comment]
(Unrelated: The Nokia didn't exactly die, but small black dots of broken pixels were starting to appear on the screen. It's still fully usable, though not exactly a super convenient OS).

**Comment by JoshTheDerf** [comment]
@Nateowami Try the latest commit, it alternates between `cover` and `contain` on varying screen sizes. There is still a bit of noticeable y-repeat though.

EDIT: Push failed. >_>
EDIT2: There we go.

Thanks a lot for the help by the way!

**Comment by Nateowami** [comment]
No problem. I kinda think the kittens were better before. Where'd you get the Latin?

**Comment by JoshTheDerf** [comment]
Atom plug-in. http://github.com/nickclaw/atom-lorem-ipsum. You jealous? :P

I'll revert the kitties.

**Comment by Nateowami** [comment]
Just FYI the hamburger menu is deformed (I think it has the border but no icon), and taping elsewhere on the page doesn't close the menu. Good night! :night_with_stars:
