### ISSUE TITLE
Medium Navbar Position Incorrect After Resizing Window

### ISSUE THREAD

**Issue by JoshTheDerf** [Tribex/tribex.github.io#2]
After resizing the window from a medium+ size to a small size, then coming back to medium, the main nav links appear below the position they are supposed to be (in Chrome at least) and are unclickable.

Obviously this is not the intended behaviour, but I cannot for the life of me figure out why this is happening. Too make matters worse, every now and then it works as expected.

Does anyone have any ideas? The relevant source would be in `src/scss/components/navigation.scss`

![image](https://cloud.githubusercontent.com/assets/5861371/7796460/fea0bfb4-0311-11e5-8576-581cfb9d302a.png)

EDIT: Confirmed as a Webkit/Chromium bug: https://code.google.com/p/chromium/issues/detail?id=411256

**Comment by Nateowami** [comment]
Reproduced in Chrome but not Firefox. Perhaps you should try StackOverflow.

**Comment by JoshTheDerf** [comment]
Aye, I can't reproduce it in Firefox either. Weird. I'll check around for similar bug reports or questions, and triple-check to make sure it's not an issue on my end that I know of before posting on SO.

**Comment by Nateowami** [comment]
I inspected the elements and found the issue was that `.main-nav` was really wide. Digging deeper it appears the only place a style that wide is on [line 28 of navigation.scss](https://github.com/Tribex/tribex.github.io/blob/master/src/scss/components/navigation.scss#L28).

**Comment by JoshTheDerf** [comment]
@Nateowami Wait, why is that an issue? `.main-nav` is the container which contains the logo, title, and `.navbox`, the div being positioned incorrectly. 

I probably ought to rename `.main-nav`, it's a bit confusing.

**Comment by Nateowami** [comment]
You're right; I mis-saw the element inspector and thought they were on separate levels. Interestingly, the menu is outside the box it's in... So the width-height stuff isn't messed up I don't think.

**Comment by JoshTheDerf** [comment]
@Nateowami Yeah. I've tried all kinds of display and float craziness and still cannot figure out what could be causing it.

I'll take a closer look tomorrow when I'm fresh. I probably made a dumb mistake somewhere, but it's strange that it only happens on Chrome.

**Comment by Nateowami** [comment]
Oddly enough, unchecking `float: right` moved it up (and to the left of course), and when I rechecked it, it stayed in the proper vertical space.

Probably a Chrome bug. My guess is that it has to do with media queries. Perhaps as a hack you could add a media query that redundantly adds the `float: right`. I don't know if that would fix it though.

**Comment by JoshTheDerf** [comment]
@Nateowami Huh, I'll look into that. Thanks for finding it!

Perhaps when the page is reflowed while changing queries, it overlaps the title a tiny bit when the media query applies, causing the bump-down. Since no more reflows happen afterwards, it stays down.

EDIT: Oh, okay, verfied webkit bug. :bug: 
http://stackoverflow.com/questions/28174782/google-chrome-float-and-media-queries

Fixed/worked around in latest commit.

**Comment by Nateowami** [comment]
Glad to hear you found a workaround!

**Comment by JoshTheDerf** [comment]
Meh, I was considering using something like that from the start, but it's not very maintainable and could easily lead to bugs in the future. It should work for now though.
