### ISSUE TITLE
Better Location for Verse

### ISSUE THREAD

**Issue by JoshTheDerf** [Tribex/tribex.github.io#3]
I'd like to make the verse more prominent, but so far every location it's been placed in seems off and doesn't align properly. (Even the current one.)

Any suggestions?

**Comment by Nateowami** [comment]
Suggestion
1. Don't put it right below 

> Stuff you probably didn't want to know but makes the page more balanced.

  Yeah, I know, that goes with "About" (and is temporary) but you at least need a separator in there.
2. "Coding Horrors" sounds like it came straight from Coding Horror, Jeff Atwood's blog. You read my mind. My RSS feed reader showed "1" right after I wrote that sentence and I went to check it out. Much better.
3. The semi colon looks a bit like an `i`, or else a person leaning on the wall. If you move it a big to the left and possibly up a few pixels I think it would be an improvement (great icon, by the way).
4. Oh, wow, I'm answering everything but what you asked. Last night it took me a long time to figure out that there was actually a scroll bar. 
5. Verse placement: Perhaps with the "Sidebar-Ipsum"?

**Comment by JoshTheDerf** [comment]
1. Good idea.
2. I added that right at the last and suddenly realized. x]
3. The semi-colon is meant to look like both a j and a person leaning on a wall. I suppose it succeeded. :D
4. Intentional, webkit-based browsers only. Should it be a couple pixels thicker?
5. Goood idea, I'll replace Sidebar-Ipsum with that.

**Comment by Nateowami** [comment]
1. OK
2. I figured.
3. Cool! Perhaps give it just a _tad_ more curve up at the end and it will look more like a j. But it's fine how it is. Great job!
4. Yeah, I saw the `-webkit` thingy for that. Perhaps a couple pixels (2 maybe?) thicker would be best.
5. I was really thinking that would have been a place you'd tried. And that it didn't fit well in a verticalish spot.

One more thing: when scaled down the `h3` titles rub the edge of the page. A bit of padding would much improve them I think.

**Comment by JoshTheDerf** [comment]
3,4,6?. Done. :smile: 
5. Let's just say I'm a bit scatterbrained... A bit...

**Comment by Nateowami** [comment]
One more thing... not a big deal but the menu disappears before it sticks.

**Comment by JoshTheDerf** [comment]
Aaand fixed as well!

I'm going to go ahead and close this issue since the original problem has been solved. :)
